<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>5c30ff66-7fb8-42ad-ad79-7e63800cc0da</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>.</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" Version="1.6.0" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.9" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Proxies" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="10.0.5" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.22.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="OpenAI" Version="2.9.1" />
    <PackageReference Include="Resend" Version="0.2.2" />
    <PackageReference Include="SendGrid" Version="9.29.3" />
    <PackageReference Include="StackExchange.Redis" Version="2.12.4" />
    <PackageReference Include="VNPAY.NET" Version="2.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Services\Ai\" />
    <Folder Include="Services\Auth\" />
    <Folder Include="Services\Cart\" />
    <Folder Include="Services\Category\" />
    <Folder Include="Services\Game\" />
    <Folder Include="Services\MoMo\" />
    <Folder Include="Services\News\" />
    <Folder Include="Services\Payment\" />
    <Folder Include="Services\Review\" />
    <Folder Include="Services\User\" />
    <Folder Include="Services\VnPay\" />
    <Folder Include="wwwroot\images\events\" />
  </ItemGroup>

</Project>
