// <auto-generated />
using System;
using GameStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Models.ChiTietGiaoDich", b =>
                {
                    b.Property<string>("MaGD")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magd");

                    b.Property<string>("MaGame")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magame");

                    b.Property<decimal>("DonGia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dongia");

                    b.HasKey("MaGD", "MaGame");

                    b.HasIndex("MaGame");

                    b.ToTable("chitietgiaodich", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magh");

                    b.Property<string>("MaGame")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magame");

                    b.Property<decimal>("DonGiaHienTai")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("dongiahientai");

                    b.HasKey("MaGH", "MaGame");

                    b.HasIndex("MaGame");

                    b.ToTable("chitietgiohang", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.DanhGia", b =>
                {
                    b.Property<string>("MaDG")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("madg");

                    b.Property<string>("MaGame")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magame");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    b.Property<int>("MucDiem")
                        .HasColumnType("int")
                        .HasColumnName("mucdiem");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaydanhgia")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nhanxet");

                    b.HasKey("MaDG");

                    b.HasIndex("MaGame");

                    b.HasIndex("MaNguoiDung", "MaGame")
                        .IsUnique();

                    b.ToTable("danhgia", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("AccessType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("accesstype");

                    b.Property<string>("Banner")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("banner");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdby");

                    b.Property<int>("CurrentParticipants")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("currentparticipants");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("endat");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("eventtype");

                    b.Property<int?>("MaxParticipants")
                        .HasColumnType("int")
                        .HasColumnName("maxparticipants");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("price");

                    b.Property<string>("PrizeCondition")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prizecondition");

                    b.Property<string>("PrizeInfo")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("prizeinfo");

                    b.Property<string>("PrizeType")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("prizetype");

                    b.Property<string>("PrizeValue")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("prizevalue");

                    b.Property<string>("RelatedGameId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("relatedgameid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("startat");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.HasKey("EventId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("RelatedGameId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.EventAnnouncement", b =>
                {
                    b.Property<int>("AnnouncementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("announcementid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnnouncementId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("CreatedBy")
                        .HasColumnType("int")
                        .HasColumnName("createdby");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.HasKey("AnnouncementId");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("EventId");

                    b.ToTable("eventannouncement", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.EventMessage", b =>
                {
                    b.Property<int>("MessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("messageid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MessageId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isdeleted");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("MessageId");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.ToTable("eventmessage", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.EventParticipant", b =>
                {
                    b.Property<int>("ParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("participantid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ParticipantId"));

                    b.Property<DateTime?>("CheckedInAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("checkedinat");

                    b.Property<int>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    b.Property<bool>("IsCheckedIn")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("ischeckedin");

                    b.Property<string>("JoinStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Joined")
                        .HasColumnName("joinstatus");

                    b.Property<DateTime>("JoinedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("joinedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<decimal>("PaidAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("paidamount");

                    b.Property<bool>("RewardGranted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("rewardgranted");

                    b.Property<DateTime?>("RewardGrantedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("rewardgrantedat");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("userid");

                    b.HasKey("ParticipantId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("eventparticipant", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Property<string>("MaGame")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magame");

                    b.Property<decimal>("Gia")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("gia");

                    b.Property<string>("Hinh")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("hinh");

                    b.Property<string>("LinkGame")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("linkgame");

                    b.Property<string>("MaTheLoai")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("matheloai");

                    b.Property<string>("MoTa")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mota");

                    b.Property<DateOnly?>("NgayRaMat")
                        .HasColumnType("date")
                        .HasColumnName("ngayramat");

                    b.Property<int>("SoLuotTai")
                        .HasColumnType("int")
                        .HasColumnName("soluottai");

                    b.Property<string>("TenGame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tengame");

                    b.HasKey("MaGame");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magh");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    b.HasKey("MaGH");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("giohang", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.IconEffect", b =>
                {
                    b.Property<int>("EffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("effectid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EffectId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat");

                    b.Property<string>("CssClass")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("cssclass");

                    b.Property<string>("EffectCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("effectcode");

                    b.Property<string>("EffectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("effectname");

                    b.Property<string>("EffectType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("effecttype");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("isactive");

                    b.Property<string>("Rarity")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("rarity");

                    b.HasKey("EffectId");

                    b.HasIndex("EffectCode")
                        .IsUnique();

                    b.ToTable("iconeffect", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.News", b =>
                {
                    b.Property<int>("NewsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("newsid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NewsId"));

                    b.Property<int>("AuthorUserId")
                        .HasColumnType("int")
                        .HasColumnName("authoruserid");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("content");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiredat");

                    b.Property<bool>("IsFeatured")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isfeatured");

                    b.Property<string>("NewsType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("newstype");

                    b.Property<DateTime>("PublishedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("publishedat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("RelatedGameId")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("relatedgameid");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Thumbnail")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updatedat");

                    b.Property<int>("ViewCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("viewcount");

                    b.HasKey("NewsId");

                    b.HasIndex("AuthorUserId");

                    b.HasIndex("RelatedGameId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("news", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("isactive");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("isverified");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("matkhau");

                    b.Property<DateOnly>("NgayDangKy")
                        .HasColumnType("date")
                        .HasColumnName("ngaydangky");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("quyen");

                    b.Property<string>("ResetCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resetcode");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("datetime2")
                        .HasColumnName("resetcodeexpiry");

                    b.Property<decimal>("SoDu")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("sodu");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tennguoidung");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("nguoidung", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.TheLoaiGame", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("matheloai");

                    b.Property<string>("TenLoaiGame")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tenloaigame");

                    b.HasKey("MaTheLoai");

                    b.ToTable("theloaigame", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ThuVienGame", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    b.Property<string>("MaGame")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magame");

                    b.Property<bool>("DaTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("datai");

                    b.Property<DateTime>("NgayMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaymua")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaNguoiDung", "MaGame");

                    b.HasIndex("MaGame");

                    b.HasIndex("MaNguoiDung", "MaGame")
                        .IsUnique();

                    b.ToTable("thuviengame", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.UserIconEffect", b =>
                {
                    b.Property<int>("UserIconEffectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("usericoneffectid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserIconEffectId"));

                    b.Property<int>("EffectId")
                        .HasColumnType("int")
                        .HasColumnName("effectid");

                    b.Property<int?>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    b.Property<DateTime?>("ExpiredAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("expiredat");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("grantedat");

                    b.Property<bool>("IsEquipped")
                        .HasColumnType("bit")
                        .HasColumnName("isequipped");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    b.HasKey("UserIconEffectId");

                    b.HasIndex("EffectId");

                    b.HasIndex("EventId");

                    b.HasIndex("MaNguoiDung");

                    b.ToTable("usericoneffect", (string)null);
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.Property<string>("MaGD")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("magd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int?>("EventId")
                        .HasColumnType("int")
                        .HasColumnName("eventid");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("GamePurchase")
                        .HasColumnName("loaigiaodich");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("int")
                        .HasColumnName("manguoidung");

                    b.Property<DateTime>("NgayMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("ngaymua")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phuongthuc");

                    b.Property<decimal>("ThanhTien")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("thanhtien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(450)")
                        .HasDefaultValue("Pending")
                        .HasColumnName("trangthai");

                    b.Property<string>("VnpTransactionNo")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("vnptransactionno");

                    b.HasKey("MaGD");

                    b.HasIndex("EventId");

                    b.HasIndex("LoaiGiaoDich");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TrangThai");

                    b.ToTable("giaodich", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGiaoDich", b =>
                {
                    b.HasOne("GiaoDich", "GiaoDich")
                        .WithMany("ChiTietGiaoDiches")
                        .HasForeignKey("MaGD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctgd_giaodich");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctgd_game");

                    b.Navigation("Game");

                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("GameStore.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chitietgiohang_giohang");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chitietgiohang_game");

                    b.Navigation("Game");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("GameStore.Models.DanhGia", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_game");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_nguoidung");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.Event", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_event_nguoidung");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("RelatedGameId")
                        .HasConstraintName("fk_event_game");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.EventAnnouncement", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventannouncement_nguoidung");

                    b.HasOne("GameStore.Models.Event", "Event")
                        .WithMany("EventAnnouncements")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventannouncement_event");

                    b.Navigation("Event");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.EventMessage", b =>
                {
                    b.HasOne("GameStore.Models.Event", "Event")
                        .WithMany("EventMessages")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventmessage_event");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventmessage_nguoidung");

                    b.Navigation("Event");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.EventParticipant", b =>
                {
                    b.HasOne("GameStore.Models.Event", "Event")
                        .WithMany("EventParticipants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_eventparticipant_event");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_eventparticipant_nguoidung");

                    b.Navigation("Event");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.HasOne("GameStore.Models.TheLoaiGame", "TheLoaiGame")
                        .WithMany("Games")
                        .HasForeignKey("MaTheLoai")
                        .HasConstraintName("fk_game_theloaigame");

                    b.Navigation("TheLoaiGame");
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithOne("GioHang")
                        .HasForeignKey("GameStore.Models.GioHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giohang_nguoidung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.News", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("AuthorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_news_nguoidung");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("RelatedGameId")
                        .HasConstraintName("fk_news_game");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.ThuVienGame", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thuvien_game");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thuvien_nguoidung");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.UserIconEffect", b =>
                {
                    b.HasOne("GameStore.Models.IconEffect", "IconEffect")
                        .WithMany("UserIconEffects")
                        .HasForeignKey("EffectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usericoneffect_effect");

                    b.HasOne("GameStore.Models.Event", "Event")
                        .WithMany("UserIconEffects")
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_usericoneffect_event");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany("UserIconEffects")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usericoneffect_user");

                    b.Navigation("Event");

                    b.Navigation("IconEffect");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.HasOne("GameStore.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .HasConstraintName("fk_giaodich_event");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giaodich_nguoidung");

                    b.Navigation("Event");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.Event", b =>
                {
                    b.Navigation("EventAnnouncements");

                    b.Navigation("EventMessages");

                    b.Navigation("EventParticipants");

                    b.Navigation("UserIconEffects");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("GameStore.Models.IconEffect", b =>
                {
                    b.Navigation("UserIconEffects");
                });

            modelBuilder.Entity("GameStore.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("GiaoDiches");

                    b.Navigation("GioHang");

                    b.Navigation("UserIconEffects");
                });

            modelBuilder.Entity("GameStore.Models.TheLoaiGame", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.Navigation("ChiTietGiaoDiches");
                });
#pragma warning restore 612, 618
        }
    }
}
