// <auto-generated />
using System;
using GameStore.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace GameStore.Migrations
{
    [DbContext(typeof(GameStoreContext))]
    partial class GameStoreContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GameStore.Models.ChiTietGiaoDich", b =>
                {
                    b.Property<string>("MaGD")
                        .HasColumnType("text")
                        .HasColumnName("magd");

                    b.Property<string>("MaGame")
                        .HasColumnType("text")
                        .HasColumnName("magame");

                    b.Property<decimal>("DonGia")
                        .HasColumnType("numeric")
                        .HasColumnName("dongia");

                    b.HasKey("MaGD", "MaGame");

                    b.HasIndex("MaGame");

                    b.ToTable("chitietgiaodich", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasColumnType("text")
                        .HasColumnName("magh");

                    b.Property<string>("MaGame")
                        .HasColumnType("text")
                        .HasColumnName("magame");

                    b.Property<decimal>("DonGiaHienTai")
                        .HasColumnType("numeric")
                        .HasColumnName("dongiahientai");

                    b.HasKey("MaGH", "MaGame");

                    b.HasIndex("MaGame");

                    b.ToTable("chitietgiohang", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.DanhGia", b =>
                {
                    b.Property<string>("MaDG")
                        .HasColumnType("text")
                        .HasColumnName("madg");

                    b.Property<string>("MaGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("magame");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("manguoidung");

                    b.Property<int>("MucDiem")
                        .HasColumnType("integer")
                        .HasColumnName("mucdiem");

                    b.Property<DateTime>("NgayDanhGia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaydanhgia")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("NhanXet")
                        .HasColumnType("text")
                        .HasColumnName("nhanxet");

                    b.HasKey("MaDG");

                    b.HasIndex("MaGame");

                    b.HasIndex("MaNguoiDung", "MaGame")
                        .IsUnique();

                    b.ToTable("danhgia", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Property<string>("MaGame")
                        .HasColumnType("text")
                        .HasColumnName("magame");

                    b.Property<decimal>("Gia")
                        .HasColumnType("numeric")
                        .HasColumnName("gia");

                    b.Property<string>("Hinh")
                        .HasColumnType("text")
                        .HasColumnName("hinh");

                    b.Property<string>("LinkGame")
                        .HasColumnType("text")
                        .HasColumnName("linkgame");

                    b.Property<string>("MaTheLoai")
                        .HasColumnType("text")
                        .HasColumnName("matheloai");

                    b.Property<string>("MoTa")
                        .HasColumnType("text")
                        .HasColumnName("mota");

                    b.Property<DateOnly?>("NgayRaMat")
                        .HasColumnType("date")
                        .HasColumnName("ngayramat");

                    b.Property<int>("SoLuotTai")
                        .HasColumnType("integer")
                        .HasColumnName("soluottai");

                    b.Property<string>("TenGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tengame");

                    b.HasKey("MaGame");

                    b.HasIndex("MaTheLoai");

                    b.ToTable("game", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.Property<string>("MaGH")
                        .HasColumnType("text")
                        .HasColumnName("magh");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("manguoidung");

                    b.HasKey("MaGH");

                    b.HasIndex("MaNguoiDung")
                        .IsUnique();

                    b.ToTable("giohang", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.NguoiDung", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("manguoidung");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaNguoiDung"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsVerified")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("isverified");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("matkhau");

                    b.Property<DateOnly>("NgayDangKy")
                        .HasColumnType("date")
                        .HasColumnName("ngaydangky");

                    b.Property<string>("Quyen")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("quyen");

                    b.Property<string>("ResetCode")
                        .HasColumnType("text")
                        .HasColumnName("resetcode");

                    b.Property<DateTime?>("ResetCodeExpiry")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resetcodeexpiry");

                    b.Property<decimal>("SoDu")
                        .HasColumnType("numeric")
                        .HasColumnName("sodu");

                    b.Property<string>("TenNguoiDung")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tennguoidung");

                    b.HasKey("MaNguoiDung");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("nguoidung", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.TheLoaiGame", b =>
                {
                    b.Property<string>("MaTheLoai")
                        .HasColumnType("text")
                        .HasColumnName("matheloai");

                    b.Property<string>("TenLoaiGame")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tenloaigame");

                    b.HasKey("MaTheLoai");

                    b.ToTable("theloaigame", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ThuVienGame", b =>
                {
                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("manguoidung");

                    b.Property<string>("MaGame")
                        .HasColumnType("text")
                        .HasColumnName("magame");

                    b.Property<bool>("DaTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("datai");

                    b.Property<DateTime>("NgayMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaymua")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("MaNguoiDung", "MaGame");

                    b.HasIndex("MaGame");

                    b.HasIndex("MaNguoiDung", "MaGame")
                        .IsUnique();

                    b.ToTable("thuviengame", (string)null);
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.Property<string>("MaGD")
                        .HasColumnType("text")
                        .HasColumnName("magd");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("createdat")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("MaNguoiDung")
                        .HasColumnType("integer")
                        .HasColumnName("manguoidung");

                    b.Property<DateTime>("NgayMua")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ngaymua")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("PhuongThuc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("phuongthuc");

                    b.Property<decimal>("ThanhTien")
                        .HasColumnType("numeric")
                        .HasColumnName("thanhtien");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("Pending")
                        .HasColumnName("trangthai");

                    b.Property<string>("VnpTransactionNo")
                        .HasColumnType("text")
                        .HasColumnName("vnptransactionno");

                    b.HasKey("MaGD");

                    b.HasIndex("MaNguoiDung");

                    b.HasIndex("TrangThai");

                    b.ToTable("giaodich", (string)null);
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGiaoDich", b =>
                {
                    b.HasOne("GiaoDich", "GiaoDich")
                        .WithMany("ChiTietGiaoDiches")
                        .HasForeignKey("MaGD")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctgd_giaodich");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ctgd_game");

                    b.Navigation("Game");

                    b.Navigation("GiaoDich");
                });

            modelBuilder.Entity("GameStore.Models.ChiTietGioHang", b =>
                {
                    b.HasOne("GameStore.Models.GioHang", "GioHang")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGH")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chitietgiohang_giohang");

                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("ChiTietGioHangs")
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_chitietgiohang_game");

                    b.Navigation("Game");

                    b.Navigation("GioHang");
                });

            modelBuilder.Entity("GameStore.Models.DanhGia", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_game");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany("DanhGias")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_danhgia_nguoidung");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.HasOne("GameStore.Models.TheLoaiGame", "TheLoaiGame")
                        .WithMany("Games")
                        .HasForeignKey("MaTheLoai")
                        .HasConstraintName("fk_game_theloaigame");

                    b.Navigation("TheLoaiGame");
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithOne("GioHang")
                        .HasForeignKey("GameStore.Models.GioHang", "MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giohang_nguoidung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.ThuVienGame", b =>
                {
                    b.HasOne("GameStore.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("MaGame")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thuvien_game");

                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_thuvien_nguoidung");

                    b.Navigation("Game");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.HasOne("GameStore.Models.NguoiDung", "NguoiDung")
                        .WithMany("GiaoDiches")
                        .HasForeignKey("MaNguoiDung")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_giaodich_nguoidung");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("GameStore.Models.Game", b =>
                {
                    b.Navigation("ChiTietGioHangs");

                    b.Navigation("DanhGias");
                });

            modelBuilder.Entity("GameStore.Models.GioHang", b =>
                {
                    b.Navigation("ChiTietGioHangs");
                });

            modelBuilder.Entity("GameStore.Models.NguoiDung", b =>
                {
                    b.Navigation("DanhGias");

                    b.Navigation("GiaoDiches");

                    b.Navigation("GioHang")
                        .IsRequired();
                });

            modelBuilder.Entity("GameStore.Models.TheLoaiGame", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("GiaoDich", b =>
                {
                    b.Navigation("ChiTietGiaoDiches");
                });
#pragma warning restore 612, 618
        }
    }
}
